account/urls.py
from django.urls import path
from . import views # importing views module from current folder

app_name = "account"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

home_page/urls.py
from django.urls import path
from . import views # importing views module from current folder

app_name = "home_page"

urlpatterns = [
    path('', views.home, name='home'),
    path('status/', views.status, name='status')
]

school_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls')),
    path('account/', include('account.urls'))
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

home_page/models.py
from django.db import models

# Create your models here.

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages, auth
from django.shortcuts import redirect

# Create your views here.

def register(request):
	if request.method == 'POST':
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']
		username = request.POST['username']
		email = request.POST['email']
		password = request.POST['password']
		conf_password = request.POST['conf_password']

		# validate password and confirm password
		if password == conf_password:
			# check if username already exists
			if User.objects.filter(username=username).exists():
				messages.error(request, "Username " + username + " is already taken")
				return redirect('account:register')
			# check if email already exists
			elif User.objects.filter(email=email).exists():
				messages.error(request, "Email already registered")
				return redirect('account:register')
			else:
				user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email, password=password)
				user.save()
				messages.success(request, "Account for " + first_name + " has been registered")
				return redirect('account:login')
		else:
			messages.error(request, "Password and confirm password fields do no match")
			return redirect('account:register')

	return render(request, 'register.html', {'register': True})

def login(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		user = auth.authenticate(username=username, password=password)

		if user is not None:
			auth.login(request, user)
			return redirect('home_page:home')
		else:
			messages.error(request, "Invalid username or password")
			return redirect('account:login')

	return render(request, 'login.html', {'login': True})

def logout(request):
	auth.logout(request)
	return redirect('home_page:home')

home_page/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
	return render(request, 'home.html', {'home': True})

def status(request):
	return render(request, 'status.html', {'status': True})

account/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block body %}
<div class="container h-75 d-flex justify-content-center align-items-center">
	<div class="col-10 col-md-6">
		<div class="card text-center shadow p-2 mb-3">
			<div class="card-body">
				<h5 class="card-title mb-4">Login</h5>
				<form method="POST" action="#">
					{% csrf_token %}
					<div class="row mb-2 justify-content-center">
						<div class="col-11">
							<input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
						</div>
					</div>
					<div class="row mb-3 justify-content-center">
						<div class="col-11">
							<input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
						</div>
					</div>
					<div class="d-grid gap-2 d-flex justify-content-center mb-3">
						<div class="col">
							<a class="btn btn-info me-2 col" type="button" href="{% url 'account:register' %}">Register</a>
							<input class="btn btn-primary col-8" type="submit" value="Login">
						</div>
					</div>
				</form>
			</div>
		</div>
		<div>
			{% for message in messages %}
			<div class="alert alert-dismissible fade show" role="alert">
				{{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			<script type="text/javascript">
				document.currentScript.previousElementSibling.classList.add(message_tags['{{ message.tags }}']);
			</script>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

account/templates/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block body %}
<div class="container d-flex justify-content-center" style="margin-top: 6vh;">
	<div class="col-10 col-md-8">
		<div>
			{% for message in messages %}
			<div class="alert alert-dismissible fade show" role="alert">
				{{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			<script type="text/javascript">
				document.currentScript.previousElementSibling.classList.add(message_tags['{{ message.tags }}']);
			</script>
			{% endfor %}
		</div>
		<div class="card text-center shadow p-2 mb-2">
			<div class="card-body">
				<h5 class="card-title mb-4">Account Registration</h5>
				<form method="POST" action="#">
					{% csrf_token %}
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name" required>
						</div>
						<div class="col">
							<input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name" required>
						</div>
					</div>
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
						</div>
					</div>
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
						</div>
					</div>
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
						</div>
					</div>
					<div class="row mb-3 justify-content-center">
						<div class="col">
							<input type="password" class="form-control" id="conf_password" name="conf_password" placeholder="Confirm Password" required>
						</div>
					</div>
					<div class="row mb-3 justify-content-center">
						<div class="col">
							<input class="btn btn-primary col-8" type="submit" value="Register">
						</div>
					</div>
				</form>
				<div>
					<p>Already have an account? <a href="{% url 'account:login' %}">Click here</a> to login.</p>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

home_page/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}
{% if user.is_authenticated %}

{% load static %}

<script src="{% static 'js/department.js' %}" type="text/javascript"></script>
<script src="{% static 'js/checkbox.js' %}" type="text/javascript"></script>

<div class="container d-flex justify-content-center" style="margin-top: 10vh; margin-bottom: 10vh;">
	<div class="col-10 col-md-8">
		<div class="card text-center shadow p-2">
			<div class="card-body">
				<h5 class="card-title mb-4">Store Form</h5>
				<form method="POST" action="{% url 'home_page:status' %}">
					{% csrf_token %}
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name" title="First Name" required>
						</div>
						<div class="col">
							<input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name" title="Last Name" required>
						</div>
					</div>
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<input type="date" class="form-control" id="date_of_birth" name="date_of_birth" placeholder="Date of Birth" title="Date of Birth" required>
						</div>
						<div class="col">
							<input type="number" min="5" max="20" class="form-control" id="age" name="age" placeholder="Age" title="Age" required>
						</div>
					</div>
					<div class="row mb-2">
						<div class="col-6">
							<div class="form-check form-check-inline">Gender: </div>
							<div class="form-check form-check-inline">
								<input class="form-check-input" type="radio" name="gender" id="gender_male" value="male">
								<label class="form-check-label" for="gender_male">Male</label>
							</div>
							<div class="form-check form-check-inline">
								<input class="form-check-input" type="radio" name="gender" id="gender_female" value="female">
								<label class="form-check-label" for="gender_female">Female</label>
							</div>
						</div>
					</div>
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<input type="tel" class="form-control" id="phone" name="phone" placeholder="Phone" title="Phone" required>
						</div>
						<div class="col">
							<input type="email" class="form-control" id="email" name="email" placeholder="Email" title="Email" required>
						</div>
					</div>
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<textarea class="form-control" id="address" name="address" rows="3" title="address" placeholder="Address" required></textarea>
						</div>
					</div>
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<select class="form-select" aria-label="department" id="department" name="department" placeholder="Department" title="Department" onchange="update_courses(this);" required>
								<!-- <option selected disabled value="">-- Department --</option> -->
							</select>
							<script type="text/javascript">
								// call initial function
								generate_departments();
							</script>
						</div>
						<div class="col">
							<select class="form-select" aria-label="course" id="course" name="course" placeholder="Course" title="Course" required>
								<option selected disabled value="">-- Select a Department  --</option>
							</select>
						</div>
					</div>
					<div class="row mb-2 justify-content-center">
						<div class="col">
							<select class="form-select" aria-label="purpose" placeholder="Purpose" title="Purpose" required>
								<option selected disabled value="">-- Purpose --</option>
								<option value="1">Enquiry</option>
								<option value="2">Order</option>
								<option value="3">Return</option>
							</select>
						</div>
					</div>
					<div class="row mb-2">
						<div class="col">
							<div class="row mb-1">
								<div class="col">
									<b>Materials:</b>
								</div>
							</div>
							<div class="row justify-content-center">
								<div class="col">
									<table class="table table-borderless checkbox_table">
										<tr>
											<td>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" name="materials" id="materials_note_book" value="Note Book" onclick="checkbox_clicked(this);">
													<label class="form-check-label" for="gender_male">Note Book</label>
												</div>
											</td>
											<td>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" name="materials" id="materials_pen" value="Pen" onclick="checkbox_clicked(this);">
													<label class="form-check-label" for="gender_male">Pen</label>
												</div>
											</td>
											<td>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" name="materials" id="materials_pencil" value="Pencil" onclick="checkbox_clicked(this);">
													<label class="form-check-label" for="gender_male">Pencil</label>
												</div>
											</td>
										</tr>
										<tr>
											<td>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" name="materials" id="materials_eraser" value="Eraser" onclick="checkbox_clicked(this);">
													<label class="form-check-label" for="gender_male">Eraser</label>
												</div>
											</td>
											<td>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" name="materials" id="materials_scale" value="Scale" onclick="checkbox_clicked(this);">
													<label class="form-check-label" for="gender_male">Scale</label>
												</div>
											</td>
											<td>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" name="materials" id="materials_text_book" value="Text Book" onclick="checkbox_clicked(this);">
													<label class="form-check-label" for="gender_male">Text Book</label>
												</div>
											</td>
										</tr>
										<tr>
											<td>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" name="materials" id="materials_lab_coat" value="Lab Coat" onclick="checkbox_clicked(this);">
													<label class="form-check-label" for="gender_male">Lab Coat</label>
												</div>
											</td>
											<td>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" name="materials" id="materials_paper" value="Paper" onclick="checkbox_clicked(this);">
													<label class="form-check-label" for="gender_male">Paper</label>
												</div>
											</td>
											<td>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" name="materials" id="materials_marker" value="Marker" onclick="checkbox_clicked(this);">
													<label class="form-check-label" for="gender_male">Marker</label>
												</div>
											</td>
										</tr>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div class="row mt-3 mb-0 justify-content-center">
						<div class="col">
							<input class="btn btn-primary col-8" type="submit" value="Submit">
						</div>
					</div>
				</form>
			</div>
		</div>
		<div>
			{% for message in messages %}
			<div class="alert alert-dismissible fade show" role="alert">
				{{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			<script type="text/javascript">
				document.currentScript.previousElementSibling.classList.add(message_tags['{{ message.tags }}']);
			</script>
			{% endfor %}
		</div>
	</div>
</div>
{% else %}
<div class="container h-75 d-flex justify-content-center align-items-center">
	<div class="col-10 col-md-6">
		<div class="card text-center shadow p-2">
			<div class="card-body">
				<h5 class="card-title">College Store</h5>
				<p class="card-text">Click button to login to your account.</p>
				<a href="{% url 'account:login' %}" class="btn btn-primary col-6">Login</a>
			</div>
			<div>
				<p><a href="{% url 'account:register' %}">Register Now</a></p>
			</div>
		</div>
	</div>
</div>
{% endif %}
{% endblock %}

home_page/templates/status.html
{% extends 'base.html' %}

{% block title %} Status {% endblock %}

{% block body %}
<div class="container h-75 d-flex justify-content-center align-items-center">
	<div class="col-10 col-md-6">
		<div class="card text-center shadow p-2">
			<div class="card-body">
				<h5 class="card-title">Order Status</h5>
				<p class="card-text">Your order has been confirmed.</p>
				<a href="{% url 'home_page:home' %}" class="btn btn-primary col-6">Return to home page</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/background.html
<!--Waves Container-->

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/background.css' %}">

<div class="" id="waves_container">
    <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="parallax">
            <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
            <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
        </g>
    </svg>
</div>

<!--Waves end-->

templates/base.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %} {% endblock %}</title>

		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

		<!-- Custom CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

		<!-- JS -->
		<script src="{% static 'js/main.js' %}" type="text/javascript"></script>
	</head>
	<body>
        {% include 'nav.html' %}

        {% block body %}
            <!-- blocks specified as 'body' will be placed here -->
        {% endblock %}

        {% include 'background.html' %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	</body>
</html>

templates/nav.html
<nav class="navbar bg-dark navbar-expand-lg sticky-top" data-bs-theme="dark">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'home_page:home' %}">College-Store</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
			<ul class="navbar-nav justify-content-end mb-2 mb-lg-0 mr-lg-2">
				<li class="nav-item">
					<a class="nav-link {% if home %}active{% endif %}" aria-current="page" href="{% url 'home_page:home' %}">Home</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Department</a>
					<ul class="dropdown-menu" id="nav_dropdown_departments">
						<!-- js generated department nav links -->
					</ul>
					<script type="text/javascript">
						// call function
						generate_nav_links();
					</script>
				</li>
				{% if user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'home_page:home' %}">Hi {{ user.username }} !</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link {% if login %}active{% endif %}" href="{% url 'account:login' %}">Login</a>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if register %}active{% endif %}" href="{% url 'account:register' %}">Register</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>